[package]
name = "test_libusb_uvc"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
crab-uvc = {path = "../../usb-device/uvc"}
uvc-frame-parser = {path = "../../utils/uvc-frame-parser"}

[target.'cfg(not(target_os = "none"))'.dependencies]
crab-usb = {workspace = true, features = ["libusb"]}
env_logger = "0.11"
log = "0.4"
tokio = {version = "1", features = ["full"]}
ffmpeg-next = "7.1.0"
image = "0.24"
